server:
  port: 8088


spring:
  application:
    name: gateway-app
  cloud:
    consul:
      discovery:
        hostname:
    gateway:
      routes:
        - id: location
#          use "urlhash" instead of "lb" to use UrlPathHashLoadBalancer and give the id value in UrlPathHashConfiguration
          uri: lb://location-writer-client
          predicates:
            - Path=/api/location/**
        - id: user
          uri: lb://user-client
          predicates:
            - Path=/api/user/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true